// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlWNmtnAeNHfFJE4cu3rpbgKkY04icvZM',
    appId: '1:953635416416:web:0edeaa64041ebbcd55d605',
    messagingSenderId: '953635416416',
    projectId: 'gluconutris',
    authDomain: 'gluconutris.firebaseapp.com',
    storageBucket: 'gluconutris.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA685cqWF0DX2PCIoCJ7p0HgDZt6QESaJw',
    appId: '1:953635416416:android:562957b1e4dfbbbb55d605',
    messagingSenderId: '953635416416',
    projectId: 'gluconutris',
    storageBucket: 'gluconutris.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtCi54-QKGK2_GRijjWkfdDGxvFzboX9c',
    appId: '1:953635416416:ios:7f1c0f96c125395355d605',
    messagingSenderId: '953635416416',
    projectId: 'gluconutris',
    storageBucket: 'gluconutris.appspot.com',
    iosBundleId: 'com.example.gluconutri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtCi54-QKGK2_GRijjWkfdDGxvFzboX9c',
    appId: '1:953635416416:ios:7f1c0f96c125395355d605',
    messagingSenderId: '953635416416',
    projectId: 'gluconutris',
    storageBucket: 'gluconutris.appspot.com',
    iosBundleId: 'com.example.gluconutri',
  );
}
